language: python
python:
    - "3.6"
before_install:
    - pip install pytest pytest-cov
    - pip install codecov
script:
    - pytest --cov=./ # run tests
after_success:
    - codecov
    - bash <(curl -s https://codecov.io/bash)